### ISSUE TITLE
Barcelona poster

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/NeuronunitOpt#15]
Hi @JustasB @vrhaynes and @rgerkin,
Here is code I am working on to get all the GLIF model Druckmann measurements.
It seems to work but takes a while.
https://github.com/russelljjarvis/neuronunit/blob/barcelona/neuronunit/aibs.py#L166-L175

I will upload pickles to the Open Science Framework when done.

Also I raised an issue about doing the same thing for all the conductance-multi-compartment models, which is harder:
https://github.com/AllenInstitute/AllenSDK/issues/415

https://github.com/AllenInstitute/AllenSDK/issues/377

**Comment by russelljjarvis** [comment]
Measuring Druckmann properties using Leaky Integrate and fire cells with their interpolated spike times is not a good idea.

**Comment by russelljjarvis** [comment]
@rgerkin  @JustasB @vrhaynes a transient error you might notice in code we are developing is a problem with requests and SSL security exemptions.

This is a convenient workaround
```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

```

**Comment by russelljjarvis** [comment]
@rgerkin This code almost computes Druckman features with allendata on NeuroML-DB models https://github.com/russelljjarvis/neuronunit/blob/barcelona/get_allen_features_from_nml_db.py#L234-L253

**Comment by russelljjarvis** [comment]
@rgerkin This code almost computes Druckman features with allendata on NeuroML-DB models https://github.com/russelljjarvis/neuronunit/blob/barcelona/get_allen_features_from_nml_db.py#L234-L253

**Comment by JustasB** [comment]
I'm not sure what is needed to close this issue.
