### ISSUE TITLE
Optimizer does not call sciunit judge

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/NeuronunitOpt#20]
Optimizer does not call sciunit judge, and circumvents judge, by calling test.compute_score with appropriate observations/predictions

As judge throws error: test class does not implement generate prediction. For the newer capacitance test that uses extract_feature, instead of generate prediction.

**Comment by rgerkin** [comment]
@russelljjarvis Could you provide a minimal working example of the workflow that leads to "test class does not implement generate prediction" for you?  Then I base my solution around solving that, while retaining all other functionality.

**Comment by rgerkin** [comment]
This might be the highest priority issue now (for me) since it is going to be the entry point to connecting the optimizer to a bunch of other sciunit/neuronunit functionality that we have discussed, as well as to an eventual code merge.  So any example of "minimal working example of the workflow that leads to "test class does not implement generate prediction" would be useful, as long as it arises for the same reason as it does in your optimizations, and even if it is just a few lines.

**Comment by russelljjarvis** [comment]
This is a situation where I don't think minimal working example is a good idea.

Because the optimizer samples a wide range of models and model attributes simply running the optimizer is a bit like a creating good test coverage.

I would edit the lines of bridge_passive and bridge_judge, above the call to compute score. Its possible to write 

```test.judge(model)``` or ```t.judge(model)```

i would insert a breakpoint above that line with 
pdb.set_trace()

**Comment by russelljjarvis** [comment]
Run code examples/use_edt.py

you will end up breakpoints I have inserted here:

https://github.com/russelljjarvis/neuronunit_opt/blob/648d033f18e3b2dece90e5610bd4f5787b3fca2f/neuronunit/optimisation/optimization_management.py#2505

https://github.com/russelljjarvis/neuronunit_opt/blob/648d033f18e3b2dece90e5610bd4f5787b3fca2f/neuronunit/optimisation/optimization_management.py#L2513

manually type out 
```
t.judge(model)
```
Observe errors and update NU tests.py or sciunit code appropriately to stop errors.

**Comment by rgerkin** [comment]
Perfect!  I will work on this.

**Comment by russelljjarvis** [comment]
Great great. That would be really helpful. 

Instead of having a breakpoint you could also use ```try, except,``` and pickle all of the models and tests for which judge fails. At the moment judge fails for 100% of model/test combinations, but at a later point when, that issue has subsided, the issue will become, making more tractable error surfaces from scores.

And also preventing the need to wrangle dictionaries, just to compute scores and preventing the need to manipulate observation standard deviations in order to make error scores proportional.

There is just so many different types of things that can go wrong with sciunit scores (for use as error gradients).

**Comment by rgerkin** [comment]
Related to #26.

**Comment by russelljjarvis** [comment]
The exception I was getting was. test does not implement sciunit judge.
There is someback ground information that is helpful to know.
When encountering this bug, I may have been pickle loading passive neuronunit tests that where made with the old sciunit protocol, and somehow I they were able to run the newer style methods that replace `generate_prediction`, ie `extract_features`, `condition_model` etc. For somereason this worked without any explicit method overriding on the pickle loaded objects. Then I got an error sciunit test does not implement `generate_prediction`.

So I think to avoid this error two things would help:
1. Rebuilding the tests (the newer sciunit is in place) but need to make fresh test objects.
2. Desired, but time consuming. Merge in the scidash changes to the active tests, to discard the older `generate_prediction` pattern, instead applying `extract_features`, `condition_model`

**Comment by russelljjarvis** [comment]
This has partially been resolved. `bridge_judge` has been deprecated in favour of judge, but two new issues have arrised.
