### ISSUE TITLE
handle obs['std']=0*units, and or pred['std'] = 0*units  in ZScore sciunit tests

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/NeuronunitOpt#27]
Related to issue defined [here](https://github.com/russelljjarvis/neuronunit/issues/26).
A debugger breakpoint created at the [same code location](https://github.com/russelljjarvis/neuronunit/blob/master/neuronunit/optimisation/optimization_management.py#L1901-L1908.
) could also find and resolve this issue.

These are both sciunit issues, but the issues equally belongs here.

**Comment by rgerkin** [comment]
@russelljjarvis I've added a check for observation['std'] == 0 in the sciunit dev branch.  

```
from sciunit.scores import ZScore                                       
import quantities as pq                                                 
observation = {'mean': 10*pq.pA, 'std': 0*pq.pA}                        
prediction = {'value': 15*pq.pA}                                        
score = ZScore.compute(observation, prediction)                         
print(score.score)
```                                                             
Now produces an `InsufficientDataScore` with score message "Observation standard deviation must be > 0".  

So things will run in the sense that a proper `Score` should now always be generated.  Of course `InsufficientDataScore` is still not a very useful score numerically.  Do you intend to convert those to the worst normalized score for optimization, or do something else with them?

**Comment by rgerkin** [comment]
Also, in the title you also mentioned `pred['std']`.  Are you using predictions with a standard deviation for something?  That key isn't used in `ZScore` anyway.

**Comment by russelljjarvis** [comment]
predictions shouldn't need a standard deviation but I found sometimes in Zscores compute_score, a standard dev in prediction helped execution for some reason. I am not that interested in finding out why.

**Comment by rgerkin** [comment]
OK, I think getting the content of `bridge_judge` to work with just `judge` should be a main focus for me, then.  I think you said that you were having problems with `ProtocolToFeaturesTest` which made this not work for you?  In #20 I am looking for an example showing this so I can fix it.

**Comment by russelljjarvis** [comment]
One matter that complicates things, is that the passive tests work with the newer extract features syntax in the passive tests class, but the active tests I have not migrated yet. I actually don't really want to be responsible for the job of updating the active tests, as it constitutes a lot of debugging work, which is not necessarily visible to people looking at this project for signs of project completion.

**Comment by rgerkin** [comment]
What is "active tests" vs "passive tests"?  

We can talk about roles and contributions on a video call.  I'll contact you on Slack to coordinate.

**Comment by russelljjarvis** [comment]
passive tests are non-spiking (typically protocol -10*qt.pA). Active require known rheobase value.

My logged in slack needs an update in Ubuntu, and I am deferring that update, email could be good for the next week.

**Comment by russelljjarvis** [comment]
I created a sciunit independent error score, with the goal of re-introducing sciunit later.

This is a more transparent way for me to locate errors in backends and other things. Its useful for unit testing and indipendently showing that optimizer works.
neuronunit/optimisation/optimization_management.py
``` python
def simple_error(observation,prediction,t):
    observation = which_thing(observation)
    prediction = which_thing(prediction)
    obs = observation['standard']
    pred = prediction['standard']
    obs = obs.rescale(pred.units)
    #pred = pred.rescale(obs.units)
    pre_error = np.sqrt((float(obs.magnitude)-float(pred.magnitude))**2)
    error = pre_error/np.abs(obs.magnitude)
    return error
```

**Comment by rgerkin** [comment]
What about this code makes it easier to debug than a sciunit Score?  

If the main obstacle is not the structure of the sciunit Score, but rather the computation it is doing (i.e. ratio and Z both being problematic in some edge cases) and all you need is a relative error measure, I could make a score class for you whose `compute` method implements the intended logic above, i.e. finding some difference between obs and pred, normalized to abs(obs).  

Also `np.sqrt((float(obs.magnitude)-float(pred.magnitude))**2)` is just squaring something and then square rooting it again immediately.  If what you are trying to do there is just make sure the resulting number is positive, I think `np.abs` should be computationally cheaper.

**Comment by russelljjarvis** [comment]
Two things 

I want the functionality of Ratio score, but I need the function to always return.

1. Breaks in the sciunit are fatal and stop optimizer execution, and I just need something that always returns. 

2. When using Z-score, I believe that the normalizing can lead to straddling values like 1.0. Which be a less informative gradient. It would be good to have an indipendent method to check this.

I agree np.abs is faster to run. I will use that.

**Comment by rgerkin** [comment]
OK, I think you are saying that you just need to focus on things that are downstream of these particular errors.  Let's plan to expect the issues with these edge cases (that raise sciunit Score exceptions but not exception in your `simple_error` code) to become visible again when sciunit Scores are put back in.

**Comment by russelljjarvis** [comment]
Yes thats a good representation of the problem.
