### ISSUE TITLE
The BlueBrain API changed but our notebook has an older call.

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/NeuronunitOpt#28]
https://github.com/russelljjarvis/neuronunit/blob/master/neuronunit/examples/notebooks/bbp.ipynb

@rgerkin I believe you emailed BBP and learned the new syntax.

It would be useful if this worked, as I was upgrading the notebook for Allen Firing Rate tests to work on real data, not simulated data.

**Comment by rgerkin** [comment]
I fixed this several months ago in `bbp.py` in scidash/neuronunit [here](https://github.com/scidash/neuronunit/commit/08fb5b44ac2efeea2f8540b971e88bdfd80f2482).  The notebook executes without any problems for me using the current version of the neuronunit dev branch.  I opened a PR between your master and the scidash dev branch, and it looks like that commit (and many others) are in there, and haven't made it into your fork yet.  It can't be merged yet, so you should either cherry-pick that commit, or just copy/paste scidash/dev's bbp.py into yours.

**Comment by russelljjarvis** [comment]
AOK great. Will do.
