### ISSUE TITLE
Make Allen Features notebook work on real data.

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/NeuronunitOpt#29]
A [newer version of Notebook](https://github.com/russelljjarvis/neuronunit/blob/master/neuronunit/examples/chapter2_needs_merge.ipynb) (pending git-push) chapter3.ipynb imports multi-spiking data and attempts to import multi-spiking data from BBP

functions in optimization_management.py need tweaking in order to handle real data, instead of simulated data.

**Comment by rgerkin** [comment]
@russelljjarvis What is the specific task here?

**Comment by russelljjarvis** [comment]
The tests that come out of ```OptMan.make_simulated_observations``` differ in dictionary structure slightly to tests I would create on the fly from Raw Allen Multi-spiking data. Ther are is a very minor difference that I can't track down. 

A way to proceed would be to try to make the real data multi-spiking tests in chapter3.ipynb, and observe reason for failure.

Execute code that successfully executes the lines below (also chapter3.ipynb) notice that code below succeeds, due to dictionary structure reasons. Do monkey patching in notebook to find out why.

``` python 
    new_tests,dtc = self.make_simulated_observations(tests,backend,rp)
            test_origin_target=dtc
            observations = dtc.preds
            target_spikes = dtc.spike_number#+10
            observation_spike = {'value': target_spikes}
            new_tests = TSD(new_tests)

            new_tests.use_rheobase_score = False
            ga_out, DO = run_ga(ranges,NGEN,new_tests,free_params=rp.keys(), MU = MU, backend=backend, selection=str('selNSGA3'), protocol={'allen':True,'elephant':False,'tsr':[target_spikes-2,target_spikes+5]})
```
https://github.com/russelljjarvis/neuronunit_opt/blob/b06f063b06f30983defb59bf1e3a8d17430f30ac/neuronunit/optimisation/optimization_management.py#L2113-L2121
