### ISSUE TITLE
Refine HH brian2 model/backend and ADexp Models.

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/NeuronunitOpt#30]

**Comment by russelljjarvis** [comment]
This means were appropriate cloning functional methods from brian adaptive exponential model 
https://github.com/russelljjarvis/neuronunit/blob/master/neuronunit/models/backends/badexp.py
to brian adaptive exponential model.
https://github.com/russelljjarvis/neuronunit/blob/master/neuronunit/models/backends/brhh.py

**Comment by russelljjarvis** [comment]
Mostly done. See 
neuronunit/examples/chapter10.ipynb

**Comment by russelljjarvis** [comment]
I would describe this task as well integrated, but not complete.

Brian2 implementations of models (adexp) have non-experimental vm offsets, that [need correction for](
https://github.com/russelljjarvis/neuronunit_opt/blob/master/neuronunit/models/backends/bhh.py#L114).


![image](https://user-images.githubusercontent.com/7786645/69466641-ff90d400-0dd8-11ea-9653-857c8ec0ae35.png)

![image](https://user-images.githubusercontent.com/7786645/69466660-133c3a80-0dd9-11ea-84be-df3424332606.png)

**Comment by rgerkin** [comment]
@russelljjarvis What is the difference between pink and red and why is pink ~40 mV higher?

**Comment by russelljjarvis** [comment]
Vr (resting membrane potential) is a model parameter e rea genes have access too. It's the offset used to downward bias Vm. Without such an offset all of our brianHH models have Vr=0mV. You can optionally hard code Vm as something you want like -65mV.

The reason for different colors is. Inject_and_plot is designed to accept whole converged populatioons (ie pareto fronts).
 
The convention is best candidate solution appears in dark color, everything else light color (light color shows variance of solutions in the  front). Since we may want to overlay the fronts from different models on the same test suite, Red,Green,Blue (dark and light, are all cycled through).

**Comment by rgerkin** [comment]
Does this optimization suite contain a RestingPotentialTest? Wouldn't that force Vr to be equal to something near the mean of the observation used in the test?

**Comment by russelljjarvis** [comment]
Yes, and yes. But notice GEN and MU is too low for any real 'forcing to occur'.

**Comment by rgerkin** [comment]
Oh, OK, so not really a bug, just expected behavior for small `MU` and `NGEN`.

**Comment by russelljjarvis** [comment]
Exactly. The HH model may need a bit more tuning/investigation though.
