### ISSUE TITLE
Sciunit scores can be unusually big for small difference between observation and prediction.

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/NeuronunitOpt#54]
![Screenshot from 2020-02-13 16-32-29](https://user-images.githubusercontent.com/7786645/74404410-82787680-4e7e-11ea-8f88-81c428d50e20.png)

If you look at the uploaded figure at the first element for Rheobase, and compare the top and bottom tables, you can see scores are allocated a bit wrong. This bug seems to have appeared post ```sciunit.log_norm.```

**Comment by rgerkin** [comment]
For both the upper and lower tables, the score for Rheobase appears to be the ratio of the prediction to the observation, i.e. the proper score (not `norm_score` not `log_norm_score`, `just the score`) for a `RatioScore`.  What kind of value were you expecting?

**Comment by russelljjarvis** [comment]
No, you are right, it probably is just the ratio score. I think I lost track of everything.
